name: Download HDFS Datanode Docker Image
on:
  workflow_dispatch: # cho phép nhấn nút chạy thủ công

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Pull and Save Docker Image
        run: |
          docker pull bde2020/hadoop-datanode:latest
          docker save bde2020/hadoop-datanode:latest -o hadoop-datanode3.2.1-java8.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hadoop-datanode3.2.1-java8-image # tên file khi tải
          path: hadoop-datanode3.2.1-java8.tar
          retention-days: 1 # tự xóa file sau 1 ngày
      
    
