name: Download MinIO (quay.io) Docker Image
on:
  workflow_dispatch: # cho phép nhấn nút chạy thủ công

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Pull and Save Docker Image
        run: |
          docker pull quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
          docker save quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1 -o minio.tar
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: minio-image # tên file khi tải
          path: minio.tar
          retention-days: 1 # tự xóa file sau 1 ngày
