name: Download Spark3 Docker Image
on:
  workflow_dispatch: # cho phép nhấn nút chạy thủ công

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Pull and Save Docker Image
        run: |
          docker pull apache/spark:v3.2.4
          docker save apache/spark:v3.2.4 -o spark3.2.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spark3.2-image # tên file khi tải
          path: spark3.2.tar
          retention-days: 1 # tự xóa file sau 1 ngày
      
    
